spring.application.name=flora
spring.datasource.url=jdbc:postgresql://localhost:5432/flora
spring.datasource.username=postgres
spring.datasource.password=Local@123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

server.servlet.context-path=/flora

app.image.allowed-extensions=jpg,jpeg,png,gif
app.image.max-size-bytes=50000000

cloudinary.cloud-name=mbnfcq1y
cloudinary.api-key=436913569828951
cloudinary.api-secret=AJDsmVUhnSTUgUUgv3Q8QaFi44A
cloudinary.folder=imai-flora


app.jwt-secret=431d98d064b5211ab932cb66325731d8cfbc091d08ce0e7e4b9e00944a37b8be
app-jwt-expiration-millisecond=604800000

flora.cors.allowed-origins=http://localhost:4200