spring.application.name=flora
spring.datasource.url=jdbc:postgresql://localhost:5432/flora
spring.datasource.username=postgres
spring.datasource.password=Local@123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

server.servlet.context-path=/flora

app.image.allowed-extensions=jpg,jpeg,png,gif
app.image.max-size-bytes=50000000

cloudinary.cloud-name=mbnfcq1y
cloudinary.api-key=436913569828951
cloudinary.api-secret=AJDsmVUhnSTUgUUgv3Q8QaFi44A
cloudinary.folder=imai-flora


app.jwt-secret=431d98d064b5211ab932cb66325731d8cfbc091d08ce0e7e4b9e00944a37b8be
app-jwt-expiration-millisecond=604800000

flora.cors.allowed-origins=http://localhost:4200

## Show full stack trace in the HTTP response (temporary, for debugging only)
#server.error.include-stacktrace=always
#server.error.include-message=always
#
## Enable DEBUG logging for your app package and Spring web/data internals
#logging.level.com.mari.flora=DEBUG
#logging.level.org.springframework.web=DEBUG
#logging.level.org.hibernate=DEBUG
#logging.level.org.springframework.data=DEBUG
#
## Make sure the console actually prints stack traces (default logback pattern usually does, but confirm)
#logging.level.root=INFO